### ISSUE TITLE
Package subpath './dist/plugin' is not defined by "exports"...

### ISSUE THREAD

**Issue by ajdintbk** [haim-io/cypress-image-diff#208]
I tried to install this package and I got error Package subpath './dist/plugin' is not defined by "exports" in <projectPath>/node-modules/cypress-image-diff-js/package.json. 

I'm using Angular 17 and Cypress 13 and installed package by running `npm i -D cypress-image-diff-js`

My cypress.config.ts looks like this: 
```
require('dotenv').config();
import getCompareSnapshotsPlugin from 'cypress-image-diff-js/dist/plugin';
import { defineConfig } from 'cypress';
export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      return getCompareSnapshotsPlugin(on, config);
    },
    baseUrl: 'http://localhost:4200',
    experimentalOriginDependencies: true,
    chromeWebSecurity: false,
    env: {
      auth0Domain: process.env['AUTH0_DOMAIN'],
      organizationName: process.env['CYPRESS_ORGANIZATION_NAME'],
      username: process.env['CYPRESS_USERNAME'],
      password: process.env['CYPRESS_PASSWORD'],
    },
  },
  video: false,
  pageLoadTimeout: 35000,
  viewportWidth: 1920,
  viewportHeight: 1080,
});
```

I added this in `commands.ts` and in `e2e.ts`
```
const compareSnapshotCommand = require('cypress-image-diff-js/dist/command');
compareSnapshotCommand();

```
When running npx cypress open I get Package subpath './dist/plugin' is not defined by "exports" in <projectPath>/node-modules/cypress-image-diff-js/package.json. 

And in tests I can not say cy.compareSnapshot(...)

What am I doing wrong here?

**Comment by krisodb** [comment]
Check https://cypress.visual-image-diff.dev/#rename-import-path
In both cases the /dist/ need to be removed from the path.

**Comment by guilhermesousa-cwi** [comment]
@krisodb Thanks friend, it helped a lot, I hadn't paid attention to that detail.

**Comment by guilhermesousa-cwi** [comment]
### In cypress.config.js I removed /dist and in the commands I had to keep /dist.

@ajdintbk 

Here it worked like this:

**cypress.config.js**

`const { defineConfig } = require("cypress");

const getCompareSnapshotsPlugin = require('cypress-image-diff-js/plugin');
module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      getCompareSnapshotsPlugin (on, config)
    },
  },
});
`
**commands.js**

`const compareSnapshotCommand = require("cypress-image-diff-js/dist/command");
compareSnapshotCommand()`

**Comment by teddythinh** [comment]
Here is my configuration based on the latest documentation:

`cypress.config.js`

```js
const { defineConfig } = require("cypress");
const getCompareSnapshotsPlugin = require('cypress-image-diff-js/plugin'); // Remove dist path

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
      return getCompareSnapshotsPlugin(on, config);
    },
  },
});
```

`cypress/support/e2e.js`

```js
// Import commands.js using ES2015 syntax:
import './commands'

// Alternatively you can use CommonJS syntax:
// require('./commands')

const compareSnapshotCommand = require('cypress-image-diff-js'); // Remove dist path
compareSnapshotCommand();
```

I'm not configuring anything in the `commands.js` file.

Package version:

```json
"devDependencies": {
  "cypress": "^13.7.1",
  "cypress-image-diff-html-report": "^2.0.2",
  "cypress-image-diff-js": "^2.1.4"
},
```

References:

- https://cypress.visual-image-diff.dev/getting-started/cypress-integration
- https://cypress.visual-image-diff.dev/getting-started/cypress-integration/javascript

**Comment by vijaycapsifi** [comment]
I get errors at both places where the import is needed 

`Error: Webpack Compilation Error`
> TS2307: Cannot find module 'cypress-image-diff-js/command' or its corresponding type declarations.

and 

> TS2307: Cannot find module 'cypress-image-diff-js/plugin' or its corresponding type declarations.

Here is my config:

`cypress-image-diff-config.ts`

```
import { defineConfig } from 'cypress';
import getCompareSnapshotsPlugin from 'cypress-image-diff-js/plugin';

export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      return getCompareSnapshotsPlugin(on, config)
    }
  }
})
```

`cypress/support/e2e.ts`

```
import './commands';
import compareSnapshotCommand from 'cypress-image-diff-js/command';
compareSnapshotCommand();
```

`Package versions`

```
"cypress": "^13.8.0",
"cypress-image-diff-html-report": "^2.0.2",
"cypress-image-diff-js": "^2.1.3",
```

**Please note I am using Cypress Cucumber to run my tests.**

**Comment by tannera** [comment]
This issue is still present in 2.2.1. Out of the box, the documented import path isn't valid.

<img width="671" alt="image" src="https://github.com/user-attachments/assets/d4db9ce1-b354-425f-98ef-dea2930d03d5">
