### ISSUE TITLE
Ability to reverse error - throw error if snapshots are the same and continue the test on different ones

### ISSUE THREAD

**Issue by Razthyae** [haim-io/cypress-image-diff#214]
In my app I actually need a functionality which is opposite to what cypress-image-diff does.
Instead of throwing error whenever snapshot is different from baseline snapshot I want to throw errors only when taken snapshot is THE SAME as baseline (with some testTreshold as well).
If baseline snapshot is different from comparison snapshot then test should continue normally.

How do I achieve that?

**Comment by kien-ht** [comment]
@Razthyae Hi, on top of my head there's no way around this at the moment unfortunately. Could you elaborate your case? Just to see if it's a solid use case for this feature
