### ISSUE TITLE
JSON report not generated when  cypress-split plugin in also used

### ISSUE THREAD

**Issue by aamir-yaseen-baba** [haim-io/cypress-image-diff#221]
JSON files are not generated, if we use cypress-split plugin for parallelization in CI. Without cypress-split plugin it works fine.
Any help is highly appreciated.
![Screenshot_2024-06-24-19-23-48-014_com android chrome-edit](https://github.com/haim-io/cypress-image-diff/assets/106054135/8572e1d2-c1c1-46c4-9c02-cc3d993c74f7)

**Comment by kien-ht** [comment]
Hi @aamir-yaseen-baba, speaking of the missing JSON report, please take a look at #183 or #177.
Secondly, parallelization is not supported at the moment, so the generated JSON might not be what you would desire. Joining JSON together is on you. We have a [related issue](https://github.com/kien-ht/cypress-image-diff-html-report/issues/4) here. Please watch or upvote this issue. If we get more feature requests about the parallelization run, we will proceed with its implementation.
