### ISSUE TITLE
'userConfig' and 'generateJsonReport' should be added to the plugin exports

### ISSUE THREAD

**Issue by fitzsimb** [haim-io/cypress-image-diff#224]
I'm trying to use this plugin, but it currently conflicts with a local "after:run" hook in my code. By exporting these two items, I can include a direct call to them and mirror the "after:run" hook in the plugin.

**Comment by fitzsimb** [comment]
It might even make sense to move the cypress hooks into their own functions and then export those. It would be cleaner and make using multiple plugins much simpler.

**Comment by kien-ht** [comment]
Hi @fitzsimb , Looks like you have encountered the multiple cypress `on` events. Please refer to this [issue](https://github.com/haim-io/cypress-image-diff/issues/183), if you're looking for a quick fix.

> It might even make sense to move the cypress hooks into their own functions and then export those. It would be cleaner and make using multiple plugins much simpler.

It would be nice to export the internal `generateJsonReport` function, however, it relies heavily on the context in which you're running it, in which case it needs the test result object, which is only available in `after:run` or `after:spec` hooks, so practically, if there is only a chance for you to invoke this `generateJsonReport` function in either of these hooks, then we might as well just set it up for you.
