### ISSUE TITLE
Are there any known issues with canvas elements?

### ISSUE THREAD

**Issue by krista-prokop** [haim-io/cypress-image-diff#225]
We have charts rendered in a canvas element and we've found they often need to be blacked out for snapshot tests because a significant difference is detected, even though visually the baseline and comparison are identical. 
I'm wondering if there are any known issues around this or if there is perhaps something we can do to make the canvas elements less sensitive.  

Here are the baseline, comparison and diff. Apologies for the different sizes; these are partial screenshots. The actual pngs are at identical sizes/resolutions. As you can see, the only thing highlighted as a diff is the line plot of the canvas' chart.

![baseline](https://github.com/user-attachments/assets/0770f08d-82a6-4429-9c66-a6d86312700e)
![comparison](https://github.com/user-attachments/assets/cc2e6102-7065-4df2-afb2-f725a300e255)
![diff](https://github.com/user-attachments/assets/c10e3ca4-b2d7-4519-bfa7-4515383ecf3b)

Additionally, the diff failure percentage isn't making sense to me - we are setting a fairly high threshold of  0.15, but the test is reporting failure at 0.039. Am I misunderstanding what the threshold arg represents? Should it align with the failure reported in the cypress logs? 

`cy.compareSnapshot('default page', .15)`
![image](https://github.com/user-attachments/assets/27e281cb-387c-465f-973a-30ab9e9859ec)

**Comment by kien-ht** [comment]
Hi @krista-prokop 

1. 
> I'm wondering if there are any known issues around this or if there is perhaps something we can do to make the canvas elements less sensitive.

There is no particular issues associated with canvas so far, or at least that's what I have experienced before. Note that any kind of animation could also cause the problem.

2.
> Additionally, the diff failure percentage isn't making sense to me - we are setting a fairly high threshold of 0.15, but the test is reporting failure at 0.039. Am I misunderstanding what the threshold arg represents? Should it align with the failure reported in the cypress logs?

The version 2 has come out, and the argument options for `cy.compareSnapshot` has changed so the old syntax doesn't work anymore, please migrate to the latest version if you can. [Please refer to this](https://cypress.visual-image-diff.dev/#new-comparesnapshot-arguments-type).

**Comment by krista-prokop** [comment]
@kien-ht  thank you so much! I'm not sure how we missed the updates to the method arguments. We can set the diff threshold quite low for canvas elements now so I think this answers both of my questions. Thanks again.
