### ISSUE TITLE
Option to set a separate direction for baseline screenshot

### ISSUE THREAD

**Issue by Nastya9js** [haim-io/cypress-image-diff#228]
Hello developers.

I hope you're doing well. I'd like to request the addition of a feature that allows to specify a separate path for storing baseline screenshots in the configuration file.

This feature would be helpful for organizing a project, as it gives the opportunity to keep and share only the baseline screenshots more efficiently. E.g.,  I faced the issue that I needed to store baseline screenshots in a cloud, where everybody can get them,  and other screenshots can be stored locally because there is no sense in sharing them 

Thank you for considering this request. Looking forward to your response.

Best regards,
Anastasiya

**Comment by kien-ht** [comment]
Hi @Nastya9js , I'm not sure if I get you right, but I assume you could just push only the baseline changes to the cloud and ignore diff and comparison folders altogether, just like you would with your version control system. Am I missing something here?
