### ISSUE TITLE
Continue tests on failed comparison

### ISSUE THREAD

**Issue by bpraznik** [haim-io/cypress-image-diff#229]
Hello.

I would like to suggest a feature, tho not sure if it is possible. I would like a config option that allows the test to continue until the end even if one comparison fails. 

My use cases are the following:

1. I'm using the `FAIL_ON_MISSING_BASELINE` flag to force developers to add baseline screenshots for new tests. To generate the baseline images we run the test suite. But since the test fails on the first missing baseline it only generates 1 baseline per run. Ideally it would go trough the whole test, generate all baselines but if one was missing fail the test at the end,
2. If we have multiple snapshots in one test, and a change affects multiple of them. The report would then only include the first failure, the developer would then fix it and only see the 2nd failure on the second run. The desired situation would again be, generate all comparisons so that we get all diffs in one run.

**Comment by kien-ht** [comment]
Maybe this is not well documented, but you could use `doNotFail` to keep the tests going regardless

```
// cypress-image-diff.config.js
const config = {
  RETRY_OPTIONS: {
    doNotFail: true
  }
};

module.exports = config;
```

Let me know if this fixes your problem

**Comment by bpraznik** [comment]
Sadly this is close but not exactly what i would want. In my ideal world the `cy.compareSnapshot` command would pass regardless, which this setting enables. But then i would want the test suite to fail if any of the comparisons would have failed.

**Comment by kien-ht** [comment]
I'm sorry I'm confused. You mean tests without baselines should fail, while tests with baselines should pass no matter what their results are?
