### ISSUE TITLE
Documentation page reported as containing malware

### ISSUE THREAD

**Issue by tryptophane** [haim-io/cypress-image-diff#230]
When I try to open the documentation page of this project https://cypress.visual-image-diff.dev/, the proxy of my company blocks the page stating it contains malware:

![image](https://github.com/user-attachments/assets/f7f9e87b-fb2a-4cad-a796-ce10d06406ce)

Because of this, we have instructions of our security team not to use this plugin. Could you please check this?

**Comment by tamasmagyar** [comment]
It's a gitbook documentation page. Is there any chance you can get more info what is it classified as malicious? _(or maybe click on the "here" to report incorrect classification)_ 

As a workaround, I can export the documentation to a pdf and commit to the repository. Would that help?

**Comment by tryptophane** [comment]
Thank you for your answer tamasmagyar.

I asked our security team for more details, and will tell you when I get an answer. In any case, yes I think it would be a good thing if the docs were included in the repo, not only regarding this issue...

**Comment by tamasmagyar** [comment]
Created a PR to add the PDF, you can use it in the meantime by downloading it: https://github.com/haim-io/cypress-image-diff/pull/231

**Comment by tryptophane** [comment]
Thank you, yes it works 😃 But I wonder, why this part of the docs needs to be on an external gitbook page or a PDF, instead of putting them into a markdown file like the other docs. In general, wouldn't it be better to have only the readme.md containing all information, instead of splitting the docs into several files? Just as an idea...

**Comment by james-robson** [comment]
I found the same issue - BitDefender detected the documentation as a phishing site.

**Comment by tamasmagyar** [comment]
Merged the documentation as PDF. Also submitted a False Positive report to BitDefender 🙏

**Comment by james-robson** [comment]
@tamasmagyar I can access the documentation page now, thank you for resolving.
